version: '3.9'

services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app
    command: sh -c "pnpm install && pnpm start"
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.payload.rule=Host(`77.223.214.122`)'
      - 'traefik.http.routers.payload.entrypoints=web'

  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    restart: always

volumes:
  node_modules:

networks:
  316-group:
    external: true
