version: '3.9'

services:
  # payload:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   labels:
  #     - 'traefik.enable=true'
  #     - 'traefik.http.routers.payload.rule=Host(`payload.local`)'
  #     - 'traefik.http.routers.payload.entrypoints=web'
  #     - 'traefik.http.services.payload.loadbalancer.server.port=3000'
  #   networks: # Connect to the 'web' network
  #     - web
  #   depends_on:
  #     - traefik
  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../traefik/traefik.yml:/etc/traefik/traefik.yml
    networks: # Connect to the 'web' network
      - web
    restart: always

  payload:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.payload.rule=Host(`77.223.214.122`)'
      - 'traefik.http.routers.payload.entrypoints=web'
      - 'traefik.http.services.payload.loadbalancer.server.port=3000' # This is essential
      - 'traefik.http.middlewares.large-upload.headers.customrequestheaders.Content-Length=524288000'
      - 'traefik.http.routers.payload.middlewares=large-upload'
    networks:
      - web
    depends_on:
      - traefik
    volumes:
      - ./public/media:/app/public/media

networks: # Define the 'web' network
  web:
    external: false
