import type { Block, Field } from 'payload'

import {
  FixedToolbarFeature,
  InlineToolbarFeature,
  lexicalEditor,
} from '@payloadcms/richtext-lexical'

import { linkGroup } from '../../fields/linkGroup'
import { textColorPickerAll } from '@/fields/textColorPicker'

export const VerticalCTAFields: Field[] = [
  {
    name: 'subtitle',
    type: 'text',
  },
  {
    name: 'title',
    type: 'text',
  },
  {
    name: 'titleClasses',
    type: 'select',
    options: [
      { label: 'Default', value: '' },
      { label: '2XL Text', value: 'text-2xl' },
      { label: '3XL Text', value: 'text-3xl' },
      { label: '4XL Text', value: 'text-4xl' },
      { label: '5XL Text', value: 'text-5xl' },
      { label: '6XL Text', value: 'text-6xl' },
      { label: '7XL Text', value: 'text-7xl' },
      { label: '8XL Text', value: 'text-8xl' },
      { label: 'MD 4XL Text', value: 'md:text-4xl' },
      { label: 'MD 5XL Text', value: 'md:text-5xl' },
      { label: 'MD 6XL Text', value: 'md:text-6xl' },
      { label: 'MD 7XL Text', value: 'md:text-7xl' },
      { label: 'MD 8XL Text', value: 'md:text-8xl' },
      { label: 'LG 4XL Text', value: 'lg:text-4xl' },
      { label: 'LG 5XL Text', value: 'lg:text-5xl' },
      { label: 'LG 6XL Text', value: 'lg:text-6xl' },
      { label: 'LG 7XL Text', value: 'lg:text-7xl' },
      { label: 'LG 8XL Text', value: 'lg:text-8xl' },
      { label: 'Medium Weight', value: 'font-medium' },
      { label: 'Semi-bold', value: 'font-semibold' },
      { label: 'Bold', value: 'font-bold' },
      { label: 'Extra-bold', value: 'font-extrabold' },
      { label: 'Black Weight', value: 'font-black' },
      { label: 'LG Medium Weight', value: 'lg:font-medium' },
      { label: 'LG Semi-bold', value: 'lg:font-semibold' },
      { label: 'LG Bold', value: 'lg:font-bold' },
      { label: 'LG Extra-bold', value: 'lg:font-extrabold' },
      { label: 'LG Black Weight', value: 'lg:font-black' },
      { label: 'Jost Font', value: 'font-jost' },
      { label: 'Urbanist Font', value: 'font-urbanist' },
      { label: 'Ubuntu Font', value: 'font-ubuntu' },
      { label: 'Inter Font', value: 'font-inter' },
      { label: 'PT None', value: 'pt-0' },
      { label: 'PT XS', value: 'pt-1' },
      { label: 'PT Small', value: 'pt-2' },
      { label: 'PT Medium', value: 'pt-4' },
      { label: 'PT Large', value: 'pt-6' },
      { label: 'PT XL', value: 'pt-8' },
      { label: 'PT 2XL', value: 'pt-10' },
      { label: 'PT 3XL', value: 'pt-12' },
      { label: 'PT 4XL', value: 'pt-16' },
      { label: 'PT 5XL', value: 'pt-20' },
      { label: 'PT 6XL', value: 'pt-24' },
      { label: 'PT 7XL', value: 'pt-32' },
      { label: 'PT 8XL', value: 'pt-40' },
      { label: 'MD PT None', value: 'md:pt-0' },
      { label: 'MD PT XS', value: 'md:pt-1' },
      { label: 'MD PT Small', value: 'md:pt-2' },
      { label: 'MD PT Medium', value: 'md:pt-4' },
      { label: 'MD PT Large', value: 'md:pt-6' },
      { label: 'MD PT XL', value: 'md:pt-8' },
      { label: 'MD PT 2XL', value: 'md:pt-10' },
      { label: 'MD PT 3XL', value: 'md:pt-12' },
      { label: 'MD PT 4XL', value: 'md:pt-16' },
      { label: 'MD PT 5XL', value: 'md:pt-20' },
      { label: 'MD PT 6XL', value: 'md:pt-24' },
      { label: 'MD PT 7XL', value: 'md:pt-32' },
      { label: 'MD PT 8XL', value: 'md:pt-40' },
      { label: 'LG PT None', value: 'lg:pt-0' },
      { label: 'LG PT XS', value: 'lg:pt-1' },
      { label: 'LG PT Small', value: 'lg:pt-2' },
      { label: 'LG PT Medium', value: 'lg:pt-4' },
      { label: 'LG PT Large', value: 'lg:pt-6' },
      { label: 'LG PT XL', value: 'lg:pt-8' },
      { label: 'LG PT 2XL', value: 'lg:pt-10' },
      { label: 'LG PT 3XL', value: 'lg:pt-12' },
      { label: 'LG PT 4XL', value: 'lg:pt-16' },
      { label: 'LG PT 5XL', value: 'lg:pt-20' },
      { label: 'LG PT 6XL', value: 'lg:pt-24' },
      { label: 'LG PT 7XL', value: 'lg:pt-32' },
      { label: 'LG PT 8XL', value: 'lg:pt-40' },
      { label: 'PB None', value: 'pb-0' },
      { label: 'PB XS', value: 'pb-1' },
      { label: 'PB Small', value: 'pb-2' },
      { label: 'PB Medium', value: 'pb-4' },
      { label: 'PB Large', value: 'pb-6' },
      { label: 'PB XL', value: 'pb-8' },
      { label: 'PB 2XL', value: 'pb-10' },
      { label: 'PB 3XL', value: 'pb-12' },
      { label: 'PB 4XL', value: 'pb-16' },
      { label: 'PB 5XL', value: 'pb-20' },
      { label: 'PB 6XL', value: 'pb-24' },
      { label: 'PB 7XL', value: 'pb-32' },
      { label: 'PB 8XL', value: 'pb-40' },
      // Padding Bottom for Medium Screens
      { label: 'PB (md) - None', value: 'md:pb-0' },
      { label: 'PB (md) - XS (1)', value: 'md:pb-1' },
      { label: 'PB (md) - S (2)', value: 'md:pb-2' },
      { label: 'PB (md) - M (4)', value: 'md:pb-4' },
      { label: 'PB (md) - L (6)', value: 'md:pb-6' },
      { label: 'PB (md) - XL (8)', value: 'md:pb-8' },
      { label: 'PB (md) - 2XL (10)', value: 'md:pb-10' },
      { label: 'PB (md) - 3XL (12)', value: 'md:pb-12' },
      { label: 'PB (md) - 4XL (16)', value: 'md:pb-16' },
      { label: 'PB (md) - 5XL (20)', value: 'md:pb-20' },
      { label: 'PB (md) - 6XL (24)', value: 'md:pb-24' },
      { label: 'PB (md) - 7XL (32)', value: 'md:pb-32' },
      { label: 'PB (md) - 8XL (40)', value: 'md:pb-40' },

      // Padding Bottom for Large Screens
      { label: 'PB (lg) - None', value: 'lg:pb-0' },
      { label: 'PB (lg) - XS (1)', value: 'lg:pb-1' },
      { label: 'PB (lg) - S (2)', value: 'lg:pb-2' },
      { label: 'PB (lg) - M (4)', value: 'lg:pb-4' },
      { label: 'PB (lg) - L (6)', value: 'lg:pb-6' },
      { label: 'PB (lg) - XL (8)', value: 'lg:pb-8' },
      { label: 'PB (lg) - 2XL (10)', value: 'lg:pb-10' },
      { label: 'PB (lg) - 3XL (12)', value: 'lg:pb-12' },
      { label: 'PB (lg) - 4XL (16)', value: 'lg:pb-16' },
      { label: 'PB (lg) - 5XL (20)', value: 'lg:pb-20' },
      { label: 'PB (lg) - 6XL (24)', value: 'lg:pb-24' },
      { label: 'PB (lg) - 7XL (32)', value: 'lg:pb-32' },
      { label: 'PB (lg) - 8XL (40)', value: 'lg:pb-40' },
    ],
    hasMany: true,
  },
  textColorPickerAll({
    overrides: {
      label: 'Title Colour',
      name: 'titleColour',
    },
  }),

  {
    name: 'description',
    type: 'richText',
    editor: lexicalEditor({
      features: ({ rootFeatures }) => {
        return [...rootFeatures, FixedToolbarFeature(), InlineToolbarFeature()]
      },
    }),
  },
  {
    name: 'descriptionClasses',
    type: 'select',
    options: [
      { label: 'Default', value: '' },
      { label: '2XL Text', value: 'text-2xl' },
      { label: '3XL Text', value: 'text-3xl' },
      { label: '4XL Text', value: 'text-4xl' },
      { label: '5XL Text', value: 'text-5xl' },
      { label: '6XL Text', value: 'text-6xl' },
      { label: '7XL Text', value: 'text-7xl' },
      { label: '8XL Text', value: 'text-8xl' },
      { label: 'MD 4XL Text', value: 'md:text-4xl' },
      { label: 'MD 5XL Text', value: 'md:text-5xl' },
      { label: 'MD 6XL Text', value: 'md:text-6xl' },
      { label: 'MD 7XL Text', value: 'md:text-7xl' },
      { label: 'MD 8XL Text', value: 'md:text-8xl' },
      { label: 'LG 4XL Text', value: 'lg:text-4xl' },
      { label: 'LG 5XL Text', value: 'lg:text-5xl' },
      { label: 'LG 6XL Text', value: 'lg:text-6xl' },
      { label: 'LG 7XL Text', value: 'lg:text-7xl' },
      { label: 'LG 8XL Text', value: 'lg:text-8xl' },
      { label: 'Medium Weight', value: 'font-medium' },
      { label: 'Semi-bold', value: 'font-semibold' },
      { label: 'Bold', value: 'font-bold' },
      { label: 'Extra-bold', value: 'font-extrabold' },
      { label: 'Black Weight', value: 'font-black' },
      { label: 'LG Medium Weight', value: 'lg:font-medium' },
      { label: 'LG Semi-bold', value: 'lg:font-semibold' },
      { label: 'LG Bold', value: 'lg:font-bold' },
      { label: 'LG Extra-bold', value: 'lg:font-extrabold' },
      { label: 'LG Black Weight', value: 'lg:font-black' },
      { label: 'Jost Font', value: 'font-jost' },
      { label: 'Urbanist Font', value: 'font-urbanist' },
      { label: 'Ubuntu Font', value: 'font-ubuntu' },
      { label: 'Inter Font', value: 'font-inter' },
      { label: 'PT None', value: 'pt-0' },
      { label: 'PT XS', value: 'pt-1' },
      { label: 'PT Small', value: 'pt-2' },
      { label: 'PT Medium', value: 'pt-4' },
      { label: 'PT Large', value: 'pt-6' },
      { label: 'PT XL', value: 'pt-8' },
      { label: 'PT 2XL', value: 'pt-10' },
      { label: 'PT 3XL', value: 'pt-12' },
      { label: 'PT 4XL', value: 'pt-16' },
      { label: 'PT 5XL', value: 'pt-20' },
      { label: 'PT 6XL', value: 'pt-24' },
      { label: 'PT 7XL', value: 'pt-32' },
      { label: 'PT 8XL', value: 'pt-40' },
      { label: 'MD PT None', value: 'md:pt-0' },
      { label: 'MD PT XS', value: 'md:pt-1' },
      { label: 'MD PT Small', value: 'md:pt-2' },
      { label: 'MD PT Medium', value: 'md:pt-4' },
      { label: 'MD PT Large', value: 'md:pt-6' },
      { label: 'MD PT XL', value: 'md:pt-8' },
      { label: 'MD PT 2XL', value: 'md:pt-10' },
      { label: 'MD PT 3XL', value: 'md:pt-12' },
      { label: 'MD PT 4XL', value: 'md:pt-16' },
      { label: 'MD PT 5XL', value: 'md:pt-20' },
      { label: 'MD PT 6XL', value: 'md:pt-24' },
      { label: 'MD PT 7XL', value: 'md:pt-32' },
      { label: 'MD PT 8XL', value: 'md:pt-40' },
      { label: 'LG PT None', value: 'lg:pt-0' },
      { label: 'LG PT XS', value: 'lg:pt-1' },
      { label: 'LG PT Small', value: 'lg:pt-2' },
      { label: 'LG PT Medium', value: 'lg:pt-4' },
      { label: 'LG PT Large', value: 'lg:pt-6' },
      { label: 'LG PT XL', value: 'lg:pt-8' },
      { label: 'LG PT 2XL', value: 'lg:pt-10' },
      { label: 'LG PT 3XL', value: 'lg:pt-12' },
      { label: 'LG PT 4XL', value: 'lg:pt-16' },
      { label: 'LG PT 5XL', value: 'lg:pt-20' },
      { label: 'LG PT 6XL', value: 'lg:pt-24' },
      { label: 'LG PT 7XL', value: 'lg:pt-32' },
      { label: 'LG PT 8XL', value: 'lg:pt-40' },
      { label: 'PB None', value: 'pb-0' },
      { label: 'PB XS', value: 'pb-1' },
      { label: 'PB Small', value: 'pb-2' },
      { label: 'PB Medium', value: 'pb-4' },
      { label: 'PB Large', value: 'pb-6' },
      { label: 'PB XL', value: 'pb-8' },
      { label: 'PB 2XL', value: 'pb-10' },
      { label: 'PB 3XL', value: 'pb-12' },
      { label: 'PB 4XL', value: 'pb-16' },
      { label: 'PB 5XL', value: 'pb-20' },
      { label: 'PB 6XL', value: 'pb-24' },
      { label: 'PB 7XL', value: 'pb-32' },
      { label: 'PB 8XL', value: 'pb-40' },
      // Padding Bottom for Medium Screens
      { label: 'PB (md) - None', value: 'md:pb-0' },
      { label: 'PB (md) - XS (1)', value: 'md:pb-1' },
      { label: 'PB (md) - S (2)', value: 'md:pb-2' },
      { label: 'PB (md) - M (4)', value: 'md:pb-4' },
      { label: 'PB (md) - L (6)', value: 'md:pb-6' },
      { label: 'PB (md) - XL (8)', value: 'md:pb-8' },
      { label: 'PB (md) - 2XL (10)', value: 'md:pb-10' },
      { label: 'PB (md) - 3XL (12)', value: 'md:pb-12' },
      { label: 'PB (md) - 4XL (16)', value: 'md:pb-16' },
      { label: 'PB (md) - 5XL (20)', value: 'md:pb-20' },
      { label: 'PB (md) - 6XL (24)', value: 'md:pb-24' },
      { label: 'PB (md) - 7XL (32)', value: 'md:pb-32' },
      { label: 'PB (md) - 8XL (40)', value: 'md:pb-40' },

      // Padding Bottom for Large Screens
      { label: 'PB (lg) - None', value: 'lg:pb-0' },
      { label: 'PB (lg) - XS (1)', value: 'lg:pb-1' },
      { label: 'PB (lg) - S (2)', value: 'lg:pb-2' },
      { label: 'PB (lg) - M (4)', value: 'lg:pb-4' },
      { label: 'PB (lg) - L (6)', value: 'lg:pb-6' },
      { label: 'PB (lg) - XL (8)', value: 'lg:pb-8' },
      { label: 'PB (lg) - 2XL (10)', value: 'lg:pb-10' },
      { label: 'PB (lg) - 3XL (12)', value: 'lg:pb-12' },
      { label: 'PB (lg) - 4XL (16)', value: 'lg:pb-16' },
      { label: 'PB (lg) - 5XL (20)', value: 'lg:pb-20' },
      { label: 'PB (lg) - 6XL (24)', value: 'lg:pb-24' },
      { label: 'PB (lg) - 7XL (32)', value: 'lg:pb-32' },
      { label: 'PB (lg) - 8XL (40)', value: 'lg:pb-40' },
    ],
    hasMany: true,
  },
  linkGroup({
    appearances: ['default', 'outline'],
    overrides: {
      maxRows: 2,
      required: false,
    },
  }),
]

export const VerticalCallToAction: Block = {
  slug: 'vcta',
  interfaceName: 'VerticalCallToActionBlock',
  fields: VerticalCTAFields,
  labels: {
    plural: 'Vertical Calls to Action',
    singular: 'Vertical Call to Action',
  },
}
