import deepMerge from '@/utilities/deepMerge'
import { Field } from 'payload'

type buttonClassesType = (options?: {
  overrides?: Record<string, unknown>
  condition?: (_, siblingData) => boolean
}) => Field

export const buttonClasses: buttonClassesType = ({
  condition = () => true,
  overrides = {},
} = {}) => {
  const buttonResult: Field = {
    name: 'buttonClasses',
    type: 'select',
    label: 'Button Classes',
    hasMany: true,
    admin: {
      condition,
    },
    options: [
      { label: 'Rounded Full', value: 'rounded-full' },
      { label: 'Rounded Large', value: 'rounded-lg' },
      { label: 'Rounded Medium', value: 'rounded' },
      { label: 'Rounded Small', value: 'rounded-sm' },
      { label: 'Border', value: 'border' },
      { label: 'Border Width 1', value: 'border-[1px]' },
      { label: 'Border Width 2', value: 'border-2' },
      { label: 'Bordered Dark', value: 'border-dark' },
      //border colors
      { label: 'Bordered Red', value: 'border-red' },
      { label: 'Bordered Green', value: 'border-green' },
      { label: 'Bordered Blue', value: 'border-blue' },
      { label: 'Bordered Yellow', value: 'border-yellow' },
      { label: 'Bordered Indigo', value: 'border-indigo' },
      { label: 'Bordered Purple', value: 'border-purple' },
      { label: 'Bordered Pink', value: 'border-pink' },
      { label: 'Bordered Gray', value: 'border-gray' },
      { label: 'Bordered Black', value: 'border-black' },
      { label: 'Bordered White', value: 'border-white' },
      //background colors
      { label: 'BG Inherit', value: 'bg-inherit' },
      { label: 'BG Current', value: 'bg-current' },
      { label: 'BG Transparent', value: 'bg-transparent' },
      { label: 'BG Black', value: 'bg-black' },
      { label: 'BG White', value: 'bg-white' },
      { label: 'BG Red', value: 'bg-red' },
      { label: 'BG Green', value: 'bg-green' },
      { label: 'BG Blue', value: 'bg-blue' },
      { label: 'BG Yellow', value: 'bg-yellow' },
      { label: 'BG Indigo', value: 'bg-indigo' },
      { label: 'BG Purple', value: 'bg-purple' },
      { label: 'BG Pink', value: 'bg-pink' },
      { label: 'BG Gray', value: 'bg-gray' },
      { label: 'BG Transparent', value: 'bg-transparent' },
      // button text colours
      { label: 'Text Black', value: 'text-black' },
      { label: 'Text White', value: 'text-white' },
      { label: 'Text Red', value: 'text-red' },
      { label: 'Text Green', value: 'text-green' },
      { label: 'Text Blue', value: 'text-blue' },
      { label: 'Text Yellow', value: 'text-yellow' },
      { label: 'Text Indigo', value: 'text-indigo' },
      { label: 'Text Purple', value: 'text-purple' },
      { label: 'Text Pink', value: 'text-pink' },
      { label: 'Text Gray', value: 'text-gray' },
      { label: 'Text White', value: 'text-white' },
      { label: 'Text Transparent', value: 'text-transparent' },
      //hover backgrounds
      { label: 'Hover bg transparent', value: 'hover:bg-transparent' },
      { label: 'Hover bg black', value: 'hover:bg-black' },
      { label: 'Hover bg white', value: 'hover:bg-white' },
      { label: 'Hover txt black', value: 'hover:text-black' },
      { label: 'Hover txt white', value: 'hover:text-white' },
      { label: 'Hover txt red', value: 'hover:text-red' },
      { label: 'Hover txt green', value: 'hover:text-green' },
      { label: 'Hover txt blue', value: 'hover:text-blue' },
      { label: 'Hover txt yellow', value: 'hover:text-yellow' },
      { label: 'Hover txt indigo', value: 'hover:text-indigo' },
      { label: 'Hover txt purple', value: 'hover:text-purple' },
      { label: 'Hover txt pink', value: 'hover:text-pink' },
      { label: 'Hover txt gray', value: 'hover:text-gray' },
      { label: 'Hover txt white', value: 'hover:text-white' },
      { label: 'Hover txt transparent', value: 'hover:text-transparent' },
      //hover border colors
      { label: 'Hover border red', value: 'hover:border-red' },
      { label: 'Hover border green', value: 'hover:border-green' },
      { label: 'Hover border blue', value: 'hover:border-blue' },
      { label: 'Hover border yellow', value: 'hover:border-yellow' },
      { label: 'Hover border indigo', value: 'hover:border-indigo' },
      { label: 'Hover border purple', value: 'hover:border-purple' },
      { label: 'Hover border pink', value: 'hover:border-pink' },
      { label: 'Hover border gray', value: 'hover:border-gray' },
      { label: 'Hover border black', value: 'hover:border-black' },
      { label: 'Hover border white', value: 'hover:border-white' },
      { label: 'Hover border transparent', value: 'hover:border-transparent' },
      { label: 'MT None', value: 'mt-0' },
      { label: 'MT XS', value: 'mt-1' },
      { label: 'MT Small', value: 'mt-2' },
      { label: 'MT Medium', value: 'mt-4' },
      { label: 'MT Large', value: 'mt-6' },
      { label: 'MT XL', value: 'mt-8' },
      { label: 'MT 2XL', value: 'mt-10' },
      { label: 'MT 3XL', value: 'mt-12' },
      { label: 'MT 4XL', value: 'mt-16' },
      { label: 'MT 5XL', value: 'mt-20' },
      { label: 'MT 6XL', value: 'mt-24' },
      { label: 'MT 7XL', value: 'mt-32' },
      { label: 'MT 8XL', value: 'mt-40' },
      { label: 'MD MT None', value: 'md:mt-0' },
      { label: 'MD MT XS', value: 'md:mt-1' },
      { label: 'MD MT Small', value: 'md:mt-2' },
      { label: 'MD MT Medium', value: 'md:mt-4' },
      { label: 'MD MT Large', value: 'md:mt-6' },
      { label: 'MD MT XL', value: 'md:mt-8' },
      { label: 'MD MT 2XL', value: 'md:mt-10' },
      { label: 'MD MT 3XL', value: 'md:mt-12' },
      { label: 'MD MT 4XL', value: 'md:mt-16' },
      { label: 'MD MT 5XL', value: 'md:mt-20' },
      { label: 'MD MT 6XL', value: 'md:mt-24' },
      { label: 'MD MT 7XL', value: 'md:mt-32' },
      { label: 'MD MT 8XL', value: 'md:mt-40' },
      { label: 'LG MT None', value: 'lg:mt-0' },
      { label: 'LG MT XS', value: 'lg:mt-1' },
      { label: 'LG MT Small', value: 'lg:mt-2' },
      { label: 'LG MT Medium', value: 'lg:mt-4' },
      { label: 'LG MT Large', value: 'lg:mt-6' },
      { label: 'LG MT XL', value: 'lg:mt-8' },
      { label: 'LG MT 2XL', value: 'lg:mt-10' },
      { label: 'LG MT 3XL', value: 'lg:mt-12' },
      { label: 'LG MT 4XL', value: 'lg:mt-16' },
      { label: 'LG MT 5XL', value: 'lg:mt-20' },
      { label: 'LG MT 6XL', value: 'lg:mt-24' },
      { label: 'LG MT 7XL', value: 'lg:mt-32' },
      { label: 'LG MT 8XL', value: 'lg:mt-40' },
      { label: 'MB None', value: 'mb-0' },
      { label: 'MB XS', value: 'mb-1' },
      { label: 'MB Small', value: 'mb-2' },
      { label: 'MB Medium', value: 'mb-4' },
      { label: 'MB Large', value: 'mb-6' },
      { label: 'MB XL', value: 'mb-8' },
      { label: 'MB 2XL', value: 'mb-10' },
      { label: 'MB 3XL', value: 'mb-12' },
      { label: 'MB 4XL', value: 'mb-16' },
      { label: 'MB 5XL', value: 'mb-20' },
      { label: 'MB 6XL', value: 'mb-24' },
      { label: 'MB 7XL', value: 'mb-32' },
      { label: 'MB 8XL', value: 'mb-40' },
      // Padding Bottom for Medium Screens
      { label: 'MB (md) - None', value: 'md:mb-0' },
      { label: 'MB (md) - XS (1)', value: 'md:mb-1' },
      { label: 'MB (md) - S (2)', value: 'md:mb-2' },
      { label: 'MB (md) - M (4)', value: 'md:mb-4' },
      { label: 'MB (md) - L (6)', value: 'md:mb-6' },
      { label: 'MB (md) - XL (8)', value: 'md:mb-8' },
      { label: 'MB (md) - 2XL (10)', value: 'md:mb-10' },
      { label: 'MB (md) - 3XL (12)', value: 'md:mb-12' },
      { label: 'MB (md) - 4XL (16)', value: 'md:mb-16' },
      { label: 'MB (md) - 5XL (20)', value: 'md:mb-20' },
      { label: 'MB (md) - 6XL (24)', value: 'md:mb-24' },
      { label: 'MB (md) - 7XL (32)', value: 'md:mb-32' },
      { label: 'MB (md) - 8XL (40)', value: 'md:mb-40' },

      // Padding Bottom for Large Screens
      { label: 'MB (lg) - None', value: 'lg:mb-0' },
      { label: 'MB (lg) - XS (1)', value: 'lg:mb-1' },
      { label: 'MB (lg) - S (2)', value: 'lg:mb-2' },
      { label: 'MB (lg) - M (4)', value: 'lg:mb-4' },
      { label: 'MB (lg) - L (6)', value: 'lg:mb-6' },
      { label: 'MB (lg) - XL (8)', value: 'lg:mb-8' },
      { label: 'MB (lg) - 2XL (10)', value: 'lg:mb-10' },
      { label: 'MB (lg) - 3XL (12)', value: 'lg:mb-12' },
      { label: 'MB (lg) - 4XL (16)', value: 'lg:mb-16' },
      { label: 'MB (lg) - 5XL (20)', value: 'lg:mb-20' },
      { label: 'MB (lg) - 6XL (24)', value: 'lg:mb-24' },
      { label: 'MB (lg) - 7XL (32)', value: 'lg:mb-32' },
      { label: 'MB (lg) - 8XL (40)', value: 'lg:mb-40' },
    ],
  }

  return deepMerge(buttonResult, overrides)
}
