import deepMerge from '@/utilities/deepMerge'
import { Field } from 'payload'

type dimensionClassesType = (options?: {
  overrides?: Record<string, unknown>
  condition?: (_, siblingData) => boolean
}) => Field

export const dimensionClasses: dimensionClassesType = ({
  condition = () => true,
  overrides = {},
} = {}) => {
  const dimensionResult: Field = {
    name: 'dimensionClasses',
    type: 'select',
    hasMany: true,
    admin: {
      condition,
    },
    options: [
      // Base width options
      { label: 'W-Auto', value: 'w-auto' },
      { label: 'W-0', value: 'w-0' },
      { label: 'W-Px', value: 'w-px' },
      { label: 'W-0.5', value: 'w-0.5' },
      { label: 'W-1', value: 'w-1' },
      { label: 'W-1.5', value: 'w-1.5' },
      { label: 'W-2', value: 'w-2' },
      { label: 'W-2.5', value: 'w-2.5' },
      { label: 'W-3', value: 'w-3' },
      { label: 'W-3.5', value: 'w-3.5' },
      { label: 'W-4', value: 'w-4' },
      { label: 'W-5', value: 'w-5' },
      { label: 'W-6', value: 'w-6' },
      { label: 'W-7', value: 'w-7' },
      { label: 'W-8', value: 'w-8' },
      { label: 'W-9', value: 'w-9' },
      { label: 'W-10', value: 'w-10' },
      { label: 'W-11', value: 'w-11' },
      { label: 'W-12', value: 'w-12' },
      { label: 'W-14', value: 'w-14' },
      { label: 'W-16', value: 'w-16' },
      { label: 'W-20', value: 'w-20' },
      { label: 'W-24', value: 'w-24' },
      { label: 'W-28', value: 'w-28' },
      { label: 'W-32', value: 'w-32' },
      { label: 'W-36', value: 'w-36' },
      { label: 'W-40', value: 'w-40' },
      { label: 'W-44', value: 'w-44' },
      { label: 'W-48', value: 'w-48' },
      { label: 'W-52', value: 'w-52' },
      { label: 'W-56', value: 'w-56' },
      { label: 'W-60', value: 'w-60' },
      { label: 'W-64', value: 'w-64' },
      { label: 'W-72', value: 'w-72' },
      { label: 'W-80', value: 'w-80' },
      { label: 'W-96', value: 'w-96' },
      { label: 'W-Full', value: 'w-full' },
      { label: 'W-Screen', value: 'w-screen' },
      { label: 'W-Min', value: 'w-min' },
      { label: 'W-Max', value: 'w-max' },
      { label: 'W-Fit', value: 'w-fit' },

      // Base height options
      { label: 'H-Auto', value: 'h-auto' },
      { label: 'H-0', value: 'h-0' },
      { label: 'H-Px', value: 'h-px' },
      { label: 'H-0.5', value: 'h-0.5' },
      { label: 'H-1', value: 'h-1' },
      { label: 'H-1.5', value: 'h-1.5' },
      { label: 'H-2', value: 'h-2' },
      { label: 'H-2.5', value: 'h-2.5' },
      { label: 'H-3', value: 'h-3' },
      { label: 'H-3.5', value: 'h-3.5' },
      { label: 'H-4', value: 'h-4' },
      { label: 'H-5', value: 'h-5' },
      { label: 'H-6', value: 'h-6' },
      { label: 'H-7', value: 'h-7' },
      { label: 'H-8', value: 'h-8' },
      { label: 'H-9', value: 'h-9' },
      { label: 'H-10', value: 'h-10' },
      { label: 'H-11', value: 'h-11' },
      { label: 'H-12', value: 'h-12' },
      { label: 'H-14', value: 'h-14' },
      { label: 'H-16', value: 'h-16' },
      { label: 'H-20', value: 'h-20' },
      { label: 'H-24', value: 'h-24' },
      { label: 'H-28', value: 'h-28' },
      { label: 'H-32', value: 'h-32' },
      { label: 'H-36', value: 'h-36' },
      { label: 'H-40', value: 'h-40' },
      { label: 'H-44', value: 'h-44' },
      { label: 'H-48', value: 'h-48' },
      { label: 'H-52', value: 'h-52' },
      { label: 'H-56', value: 'h-56' },
      { label: 'H-60', value: 'h-60' },
      { label: 'H-64', value: 'h-64' },
      { label: 'H-72', value: 'h-72' },
      { label: 'H-80', value: 'h-80' },
      { label: 'H-96', value: 'h-96' },
      { label: 'H-Full', value: 'h-full' },
      { label: 'H-Screen', value: 'h-screen' },
      { label: 'H-Min', value: 'h-min' },
      { label: 'H-Max', value: 'h-max' },
      { label: 'H-Fit', value: 'h-fit' },

      // SM breakpoint
      { label: 'SM:W-Auto', value: 'sm:w-auto' },
      { label: 'SM:W-0', value: 'sm:w-0' },
      { label: 'SM:W-Px', value: 'sm:w-px' },
      { label: 'SM:W-0.5', value: 'sm:w-0.5' },
      { label: 'SM:W-1', value: 'sm:w-1' },
      { label: 'SM:W-1.5', value: 'sm:w-1.5' },
      { label: 'SM:W-2', value: 'sm:w-2' },
      { label: 'SM:W-2.5', value: 'sm:w-2.5' },
      { label: 'SM:W-3', value: 'sm:w-3' },
      { label: 'SM:W-3.5', value: 'sm:w-3.5' },
      { label: 'SM:W-4', value: 'sm:w-4' },
      { label: 'SM:W-5', value: 'sm:w-5' },
      { label: 'SM:W-6', value: 'sm:w-6' },
      { label: 'SM:W-7', value: 'sm:w-7' },
      { label: 'SM:W-8', value: 'sm:w-8' },
      { label: 'SM:W-9', value: 'sm:w-9' },
      { label: 'SM:W-10', value: 'sm:w-10' },
      { label: 'SM:W-11', value: 'sm:w-11' },
      { label: 'SM:W-12', value: 'sm:w-12' },
      { label: 'SM:W-14', value: 'sm:w-14' },
      { label: 'SM:W-16', value: 'sm:w-16' },
      { label: 'SM:W-20', value: 'sm:w-20' },
      { label: 'SM:W-24', value: 'sm:w-24' },
      { label: 'SM:W-28', value: 'sm:w-28' },
      { label: 'SM:W-32', value: 'sm:w-32' },
      { label: 'SM:W-36', value: 'sm:w-36' },
      { label: 'SM:W-40', value: 'sm:w-40' },
      { label: 'SM:W-44', value: 'sm:w-44' },
      { label: 'SM:W-48', value: 'sm:w-48' },
      { label: 'SM:W-52', value: 'sm:w-52' },
      { label: 'SM:W-56', value: 'sm:w-56' },
      { label: 'SM:W-60', value: 'sm:w-60' },
      { label: 'SM:W-64', value: 'sm:w-64' },
      { label: 'SM:W-72', value: 'sm:w-72' },
      { label: 'SM:W-80', value: 'sm:w-80' },
      { label: 'SM:W-96', value: 'sm:w-96' },
      { label: 'SM:W-Full', value: 'sm:w-full' },
      { label: 'SM:W-Screen', value: 'sm:w-screen' },
      { label: 'SM:W-Min', value: 'sm:w-min' },
      { label: 'SM:W-Max', value: 'sm:w-max' },
      { label: 'SM:W-Fit', value: 'sm:w-fit' },

      { label: 'SM:H-Auto', value: 'sm:h-auto' },
      { label: 'SM:H-16', value: 'sm:h-16' },
      { label: 'SM:H-20', value: 'sm:h-20' },
      { label: 'SM:H-24', value: 'sm:h-24' },
      { label: 'SM:H-28', value: 'sm:h-28' },
      { label: 'SM:H-32', value: 'sm:h-32' },
      { label: 'SM:H-36', value: 'sm:h-36' },
      { label: 'SM:H-40', value: 'sm:h-40' },
      { label: 'SM:H-44', value: 'sm:h-44' },
      { label: 'SM:H-48', value: 'sm:h-48' },
      { label: 'SM:H-52', value: 'sm:h-52' },
      { label: 'SM:H-56', value: 'sm:h-56' },
      { label: 'SM:H-60', value: 'sm:h-60' },
      { label: 'SM:H-64', value: 'sm:h-64' },
      { label: 'SM:H-72', value: 'sm:h-72' },
      { label: 'SM:H-80', value: 'sm:h-80' },
      { label: 'SM:H-96', value: 'sm:h-96' },
      { label: 'SM:H-Full', value: 'sm:h-full' },
      { label: 'SM:H-Screen', value: 'sm:h-screen' },
      { label: 'SM:H-Min', value: 'sm:h-min' },
      { label: 'SM:H-Max', value: 'sm:h-max' },
      { label: 'SM:H-Fit', value: 'sm:h-fit' },

      // MD breakpoint
      { label: 'MD:W-Auto', value: 'md:w-auto' },
      { label: 'MD:W-0', value: 'md:w-0' },
      { label: 'MD:W-Px', value: 'md:w-px' },
      { label: 'MD:W-0.5', value: 'md:w-0.5' },
      { label: 'MD:W-1', value: 'md:w-1' },
      { label: 'MD:W-1.5', value: 'md:w-1.5' },
      { label: 'MD:W-2', value: 'md:w-2' },
      { label: 'MD:W-2.5', value: 'md:w-2.5' },
      { label: 'MD:W-3', value: 'md:w-3' },
      { label: 'MD:W-3.5', value: 'md:w-3.5' },
      { label: 'MD:W-4', value: 'md:w-4' },
      { label: 'MD:W-5', value: 'md:w-5' },
      { label: 'MD:W-6', value: 'md:w-6' },
      { label: 'MD:W-7', value: 'md:w-7' },
      { label: 'MD:W-8', value: 'md:w-8' },
      { label: 'MD:W-9', value: 'md:w-9' },
      { label: 'MD:W-10', value: 'md:w-10' },
      { label: 'MD:W-11', value: 'md:w-11' },
      { label: 'MD:W-12', value: 'md:w-12' },
      { label: 'MD:W-14', value: 'md:w-14' },
      { label: 'MD:W-16', value: 'md:w-16' },
      { label: 'MD:W-20', value: 'md:w-20' },
      { label: 'MD:W-24', value: 'md:w-24' },
      { label: 'MD:W-28', value: 'md:w-28' },
      { label: 'MD:W-32', value: 'md:w-32' },
      { label: 'MD:W-36', value: 'md:w-36' },
      { label: 'MD:W-40', value: 'md:w-40' },
      { label: 'MD:W-44', value: 'md:w-44' },
      { label: 'MD:W-48', value: 'md:w-48' },
      { label: 'MD:W-52', value: 'md:w-52' },
      { label: 'MD:W-56', value: 'md:w-56' },
      { label: 'MD:W-60', value: 'md:w-60' },
      { label: 'MD:W-64', value: 'md:w-64' },
      { label: 'MD:W-72', value: 'md:w-72' },
      { label: 'MD:W-80', value: 'md:w-80' },
      { label: 'MD:W-96', value: 'md:w-96' },
      { label: 'MD:W-Full', value: 'md:w-full' },
      { label: 'MD:W-Screen', value: 'md:w-screen' },
      { label: 'MD:W-Min', value: 'md:w-min' },
      { label: 'MD:W-Max', value: 'md:w-max' },
      { label: 'MD:W-Fit', value: 'md:w-fit' },

      { label: 'MD:H-Auto', value: 'md:h-auto' },
      { label: 'MD:H-0', value: 'md:h-0' },
      { label: 'MD:H-Px', value: 'md:h-px' },
      { label: 'MD:H-0.5', value: 'md:h-0.5' },
      { label: 'MD:H-1', value: 'md:h-1' },
      { label: 'MD:H-1.5', value: 'md:h-1.5' },
      { label: 'MD:H-2', value: 'md:h-2' },
      { label: 'MD:H-2.5', value: 'md:h-2.5' },
      { label: 'MD:H-3', value: 'md:h-3' },
      { label: 'MD:H-3.5', value: 'md:h-3.5' },
      { label: 'MD:H-4', value: 'md:h-4' },
      { label: 'MD:H-5', value: 'md:h-5' },
      { label: 'MD:H-6', value: 'md:h-6' },
      { label: 'MD:H-7', value: 'md:h-7' },
      { label: 'MD:H-8', value: 'md:h-8' },
      { label: 'MD:H-9', value: 'md:h-9' },
      { label: 'MD:H-10', value: 'md:h-10' },
      { label: 'MD:H-11', value: 'md:h-11' },
      { label: 'MD:H-12', value: 'md:h-12' },
      { label: 'MD:H-14', value: 'md:h-14' },
      { label: 'MD:H-16', value: 'md:h-16' },
      { label: 'MD:H-20', value: 'md:h-20' },
      { label: 'MD:H-24', value: 'md:h-24' },
      { label: 'MD:H-28', value: 'md:h-28' },
      { label: 'MD:H-32', value: 'md:h-32' },
      { label: 'MD:H-36', value: 'md:h-36' },
      { label: 'MD:H-40', value: 'md:h-40' },
      { label: 'MD:H-44', value: 'md:h-44' },
      { label: 'MD:H-48', value: 'md:h-48' },
      { label: 'MD:H-52', value: 'md:h-52' },
      { label: 'MD:H-56', value: 'md:h-56' },
      { label: 'MD:H-60', value: 'md:h-60' },
      { label: 'MD:H-64', value: 'md:h-64' },
      { label: 'MD:H-72', value: 'md:h-72' },
      { label: 'MD:H-80', value: 'md:h-80' },
      { label: 'MD:H-96', value: 'md:h-96' },
      { label: 'MD:H-Full', value: 'md:h-full' },
      { label: 'MD:H-Screen', value: 'md:h-screen' },
      { label: 'MD:H-Min', value: 'md:h-min' },
      { label: 'MD:H-Max', value: 'md:h-max' },
      { label: 'MD:H-Fit', value: 'md:h-fit' },

      // LG breakpoint
      { label: 'LG:W-Auto', value: 'lg:w-auto' },
      { label: 'LG:W-16', value: 'lg:w-16' },
      { label: 'LG:W-20', value: 'lg:w-20' },
      { label: 'LG:W-24', value: 'lg:w-24' },
      { label: 'LG:W-28', value: 'lg:w-28' },
      { label: 'LG:W-32', value: 'lg:w-32' },
      { label: 'LG:W-36', value: 'lg:w-36' },
      { label: 'LG:W-40', value: 'lg:w-40' },
      { label: 'LG:W-44', value: 'lg:w-44' },
      { label: 'LG:W-48', value: 'lg:w-48' },
      { label: 'LG:W-52', value: 'lg:w-52' },
      { label: 'LG:W-56', value: 'lg:w-56' },
      { label: 'LG:W-60', value: 'lg:w-60' },
      { label: 'LG:W-64', value: 'lg:w-64' },
      { label: 'LG:W-72', value: 'lg:w-72' },
      { label: 'LG:W-80', value: 'lg:w-80' },
      { label: 'LG:W-96', value: 'lg:w-96' },
      { label: 'LG:W-Full', value: 'lg:w-full' },
      { label: 'LG:W-Screen', value: 'lg:w-screen' },
      { label: 'LG:W-Min', value: 'lg:w-min' },
      { label: 'LG:W-Max', value: 'lg:w-max' },
      { label: 'LG:W-Fit', value: 'lg:w-fit' },

      { label: 'LG:H-Auto', value: 'lg:h-auto' },
      { label: 'LG:H-16', value: 'lg:h-16' },
      { label: 'LG:H-20', value: 'lg:h-20' },
      { label: 'LG:H-24', value: 'lg:h-24' },
      { label: 'LG:H-28', value: 'lg:h-28' },
      { label: 'LG:H-32', value: 'lg:h-32' },
      { label: 'LG:H-36', value: 'lg:h-36' },
      { label: 'LG:H-40', value: 'lg:h-40' },
      { label: 'LG:H-44', value: 'lg:h-44' },
      { label: 'LG:H-48', value: 'lg:h-48' },
      { label: 'LG:H-52', value: 'lg:h-52' },
      { label: 'LG:H-56', value: 'lg:h-56' },
      { label: 'LG:H-60', value: 'lg:h-60' },
      { label: 'LG:H-64', value: 'lg:h-64' },
      { label: 'LG:H-72', value: 'lg:h-72' },
      { label: 'LG:H-80', value: 'lg:h-80' },
      { label: 'LG:H-96', value: 'lg:h-96' },
      { label: 'LG:H-Full', value: 'lg:h-full' },
      { label: 'LG:H-Screen', value: 'lg:h-screen' },
      { label: 'LG:H-Min', value: 'lg:h-min' },
      { label: 'LG:H-Max', value: 'lg:h-max' },
      { label: 'LG:H-Fit', value: 'lg:h-fit' },

      // XL breakpoint
      { label: 'XL:W-Auto', value: 'xl:w-auto' },
      { label: 'XL:W-16', value: 'xl:w-16' },
      { label: 'XL:W-20', value: 'xl:w-20' },
      { label: 'XL:W-24', value: 'xl:w-24' },
      { label: 'XL:W-28', value: 'xl:w-28' },
      { label: 'XL:W-32', value: 'xl:w-32' },
      { label: 'XL:W-36', value: 'xl:w-36' },
      { label: 'XL:W-40', value: 'xl:w-40' },
      { label: 'XL:W-44', value: 'xl:w-44' },
      { label: 'XL:W-48', value: 'xl:w-48' },
      { label: 'XL:W-52', value: 'xl:w-52' },
      { label: 'XL:W-56', value: 'xl:w-56' },
      { label: 'XL:W-60', value: 'xl:w-60' },
      { label: 'XL:W-64', value: 'xl:w-64' },
      { label: 'XL:W-72', value: 'xl:w-72' },
      { label: 'XL:W-80', value: 'xl:w-80' },
      { label: 'XL:W-96', value: 'xl:w-96' },
      { label: 'XL:W-Full', value: 'xl:w-full' },
      { label: 'XL:W-Screen', value: 'xl:w-screen' },
      { label: 'XL:W-Min', value: 'xl:w-min' },
      { label: 'XL:W-Max', value: 'xl:w-max' },
      { label: 'XL:W-Fit', value: 'xl:w-fit' },

      { label: 'XL:H-Auto', value: 'xl:h-auto' },
      { label: 'XL:H-16', value: 'xl:h-16' },
      { label: 'XL:H-20', value: 'xl:h-20' },
      { label: 'XL:H-24', value: 'xl:h-24' },
      { label: 'XL:H-28', value: 'xl:h-28' },
      { label: 'XL:H-32', value: 'xl:h-32' },
      { label: 'XL:H-36', value: 'xl:h-36' },
      { label: 'XL:H-40', value: 'xl:h-40' },
      { label: 'XL:H-44', value: 'xl:h-44' },
      { label: 'XL:H-48', value: 'xl:h-48' },
      { label: 'XL:H-52', value: 'xl:h-52' },
      { label: 'XL:H-56', value: 'xl:h-56' },
      { label: 'XL:H-60', value: 'xl:h-60' },
      { label: 'XL:H-64', value: 'xl:h-64' },
      { label: 'XL:H-72', value: 'xl:h-72' },
      { label: 'XL:H-80', value: 'xl:h-80' },
      { label: 'XL:H-96', value: 'xl:h-96' },
      { label: 'XL:H-Full', value: 'xl:h-full' },
      { label: 'XL:H-Screen', value: 'xl:h-screen' },
      { label: 'XL:H-Min', value: 'xl:h-min' },
      { label: 'XL:H-Max', value: 'xl:h-max' },
      { label: 'XL:H-Fit', value: 'xl:h-fit' },
    ],
  }

  return deepMerge(dimensionResult, overrides)
}
